# Generated by Django 4.1.2 on 2022-10-11 15:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_alter_restaurant_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 11, 18, 12, 49, 80509)),
        ),
    ]
